<%@ page pageEncoding="UTF-8"%>
<div class="topbar">
<div class="navi">
<ul>
<li><a href="/sems/subject/list.bit?pageNo=1&pageSize=10">
<span class="icon icon-subject"></span><span class="text">과목정보</span></a></li>
<li><a href="/sems/course/list.bit?pageNo=1&pageSize=10">
<span class="icon icon-course"></span><span class="text">과정정보</span></a></li>
<li><a href="/sems/user/list.bit?pageNo=1&pageSize=10">
<span class="icon icon-user"></span><span class="text">사용자정보</span></a></li>
</ul>
</div>
</div>
<div class="content">